/**
 * 歴史分岐シナリオ「元亀元年・家康」の版 2 の保存データ（信頼に家臣の 3 人がいて、副目標の欄が無い形）。
 * 版 3 に上げる前のコード（コミット 2480b97 の toIeyasuSaveData）が実際に書いた文字列をそのまま写したもの（手で書いた物ではない）。
 * 手順は tests/proto3d-ieyasu-helpers.ts の ieyasuToMuster／ieyasuToAftermath と IeyasuSaveStore.save。
 * 版 3 のコードで読めること・読んで版 3 で保存し直しても既存の値が変わらないことを確かめるのに使う。
 */

/** 支度・C 自領・約束の返事の前（メニューから保存） */
export const IEYASU_V2_MUSTER_HOME =
    '{"version":2,"scenario":"ieyasu1570","savedAt":"2026-09-29T02:00:00.000Z","point":"manual","playTimeSec":0,"phase":"muster","policy":"home","trust":{"oda":30,"asai":10,"tadakatsu":40,"sakai":40,"ishikawa":40,"sakakibara":40},"troops":{"honjin":300,"tadakatsu":450,"yumi":350,"reserve":300},"characters":{"ieyasu":"alive","tadakatsu":"alive","nobunaga":"alive","nagamasa":"alive"},"talked":{"explore.tadakatsu":true,"council.council":true},"pledge":null,"battle":null,"battleId":null,"appliedBattleId":null,"support":null,"ending":null,"explore":null}';

/** 戦後・A 織田・勝利・約束を守った（援兵あり） */
export const IEYASU_V2_AFTERMATH_ODA =
    '{"version":2,"scenario":"ieyasu1570","savedAt":"2026-09-29T02:00:00.000Z","point":"aftermath","playTimeSec":0,"phase":"aftermath","policy":"oda","trust":{"oda":70,"asai":-5,"tadakatsu":45,"sakai":45,"ishikawa":45,"sakakibara":40},"troops":{"honjin":290,"tadakatsu":410,"yumi":330,"reserve":300},"characters":{"ieyasu":"alive","tadakatsu":"alive","nobunaga":"alive","nagamasa":"alive"},"talked":{"explore.tadakatsu":true,"council.council":true,"muster.oda_envoy":true,"muster.gate":true},"pledge":{"accepted":true,"partner":"oda","targetId":"a_oda","result":"kept"},"battle":{"result":"victory","reason":"enemy_hq_routed","elapsedSec":300,"units":[{"id":"t_honjin","side":"ally","clan":"tokugawa","startStrength":300,"endStrength":240,"status":"ready","leaderId":"ieyasu"},{"id":"t_tadakatsu","side":"ally","clan":"tokugawa","startStrength":450,"endStrength":360,"status":"ready","leaderId":"tadakatsu"},{"id":"t_yumi","side":"ally","clan":"tokugawa","startStrength":350,"endStrength":280,"status":"ready"},{"id":"a_oda","side":"ally","clan":"oda","startStrength":400,"endStrength":320,"status":"ready"},{"id":"e_nagamasa","side":"enemy","clan":"asai","startStrength":400,"endStrength":320,"status":"routed","leaderId":"nagamasa"},{"id":"e_asai_sente","side":"enemy","clan":"asai","startStrength":600,"endStrength":480,"status":"ready"},{"id":"e_asai_yumi","side":"enemy","clan":"asai","startStrength":300,"endStrength":240,"status":"ready"},{"id":"e_asakura","side":"enemy","clan":"asakura","startStrength":450,"endStrength":360,"status":"ready"}],"pledge":{"targetId":"a_oda","result":"kept"}},"battleId":"ieyasu1570-field","appliedBattleId":"ieyasu1570-field","support":{"reinforcement":true,"from":"oda","recovered":150,"carryOver":["policy_oda","pledge_kept","reinforcement_oda"]},"ending":null,"explore":null}';

/** 結末・C 自領・撤退・約束を引き受けない */
export const IEYASU_V2_ENDING_HOME =
    '{"version":2,"scenario":"ieyasu1570","savedAt":"2026-09-29T02:00:00.000Z","point":"ending","playTimeSec":0,"phase":"ending","policy":"home","trust":{"oda":20,"asai":10,"tadakatsu":40,"sakai":40,"ishikawa":40,"sakakibara":40},"troops":{"honjin":240,"tadakatsu":360,"yumi":280,"reserve":240},"characters":{"ieyasu":"alive","tadakatsu":"alive","nobunaga":"alive","nagamasa":"alive"},"talked":{"explore.tadakatsu":true,"council.council":true,"muster.tadakatsu":true,"muster.gate":true,"aftermath.tadakatsu":true},"pledge":{"accepted":false,"partner":"tadakatsu","targetId":"t_reserve","result":"declined"},"battle":{"result":"retreat","reason":"ordered_retreat","elapsedSec":300,"units":[{"id":"t_honjin","side":"ally","clan":"tokugawa","startStrength":300,"endStrength":240,"status":"withdrawn","leaderId":"ieyasu"},{"id":"t_tadakatsu","side":"ally","clan":"tokugawa","startStrength":450,"endStrength":360,"status":"withdrawn","leaderId":"tadakatsu"},{"id":"t_yumi","side":"ally","clan":"tokugawa","startStrength":350,"endStrength":280,"status":"withdrawn"},{"id":"t_reserve","side":"ally","clan":"tokugawa","startStrength":300,"endStrength":240,"status":"withdrawn"},{"id":"e_ronin_hq","side":"enemy","clan":"ronin","startStrength":350,"endStrength":280,"status":"ready"},{"id":"e_ronin_yari","side":"enemy","clan":"ronin","startStrength":550,"endStrength":440,"status":"ready"},{"id":"e_ronin_yumi","side":"enemy","clan":"ronin","startStrength":300,"endStrength":240,"status":"ready"},{"id":"e_ronin_kiba","side":"enemy","clan":"ronin","startStrength":250,"endStrength":200,"status":"ready"}]},"battleId":"ieyasu1570-field","appliedBattleId":"ieyasu1570-field","support":{"reinforcement":false,"from":null,"recovered":0,"carryOver":["policy_home","pledge_declined"]},"ending":"retreat","explore":null}';
