/**
 * 形式の版 1 の保存データ（変更前のコード aa6d550 の toSaveData が書いたものをそのまま写した。テストの本体ではない）。
 * 版 2（合戦の id・反映の済み印を足した）になっても、これが読めて続きから遊べることを確かめる。
 */

/** 版 1・戦後の自動保存（大森 × 敗北） */
export const V1_AFTERMATH_OMORI_DEFEAT = '{"version":1,"savedAt":"2026-09-28T10:00:00.000Z","point":"aftermath","playTimeSec":0,"phase":"aftermath","alliance":"omori","relations":{"tashiro":-20,"omori":0,"washio":-60},"troops":{"honjin":240,"genzo":400,"shinpachi":280,"reserve":300},"characters":{"hero":"wounded","genzo":"wounded","shinpachi":"alive","tashiro_envoy":"alive","omori_envoy":"alive","washio_gen":"alive"},"talked":{"explore.genzo":true,"explore.shinpachi":true,"council.council":true,"muster.gate":true},"battle":{"result":"defeat","reason":"ally_hq_routed","elapsedSec":300,"units":[{"id":"a_hq","side":"ally","clan":"kotosaka","startStrength":300,"endStrength":240,"status":"routed","leaderId":"hero"},{"id":"a_genzo","side":"ally","clan":"kotosaka","startStrength":500,"endStrength":400,"status":"ready","leaderId":"genzo"},{"id":"a_shinpachi","side":"ally","clan":"kotosaka","startStrength":350,"endStrength":280,"status":"ready","leaderId":"shinpachi"},{"id":"a_omori","side":"ally","clan":"omori","startStrength":400,"endStrength":320,"status":"ready","leaderId":"omori_envoy"},{"id":"e_hq","side":"enemy","clan":"washio","startStrength":350,"endStrength":280,"status":"ready","leaderId":"washio_gen"},{"id":"e_sente","side":"enemy","clan":"washio","startStrength":550,"endStrength":440,"status":"ready"},{"id":"e_yumi","side":"enemy","clan":"washio","startStrength":350,"endStrength":280,"status":"ready"},{"id":"e_tashiro","side":"enemy","clan":"tashiro","startStrength":250,"endStrength":200,"status":"ready","leaderId":"tashiro_envoy"}]},"ending":null,"explore":null}';

/** 版 1・出陣前の自動保存（田代） */
export const V1_DEPARTURE_TASHIRO = '{"version":1,"savedAt":"2026-09-28T09:00:00.000Z","point":"departure","playTimeSec":0,"phase":"battle","alliance":"tashiro","relations":{"tashiro":10,"omori":10,"washio":-60},"troops":{"honjin":300,"genzo":500,"shinpachi":350,"reserve":300},"characters":{"hero":"alive","genzo":"alive","shinpachi":"alive","tashiro_envoy":"alive","omori_envoy":"alive","washio_gen":"alive"},"talked":{"explore.genzo":true,"explore.shinpachi":true,"council.council":true,"muster.gate":true},"battle":null,"ending":null,"explore":null}';
