/**
 * 歴史分岐シナリオ「元亀元年・家康」の版 1 の保存データ（'koto-sengoku/3d-ieyasu1570'）。
 * 版 2 に上げる前のコード（toIeyasuSaveData）が実際に書いた文字列をそのまま写したもの（手で書いた物ではない）。
 * 版 2 のコードで読めること・読んで版 2 で保存し直しても既存の値が変わらないことを確かめるのに使う。
 */

/** 支度・A 織田・約束の返事の前（メニューから保存） */
export const IEYASU_V1_MUSTER_ODA =
    '{"version":1,"scenario":"ieyasu1570","savedAt":"2026-09-28T11:00:00.000Z","point":"manual","playTimeSec":321,"phase":"muster","policy":"oda","trust":{"oda":30,"asai":10,"tadakatsu":40},"troops":{"honjin":300,"tadakatsu":450,"yumi":350,"reserve":300},"characters":{"ieyasu":"alive","tadakatsu":"alive","nobunaga":"alive","nagamasa":"alive"},"talked":{"explore.tadakatsu":true,"explore.oda_envoy":true,"council.council":true},"pledge":null,"battle":null,"battleId":null,"appliedBattleId":null,"support":null,"ending":null,"explore":{"x":1.5,"z":-3,"heading":0.5}}';

/** 出陣前の自動保存・C 自領・約束を引き受けない */
export const IEYASU_V1_DEPARTURE_HOME =
    '{"version":1,"scenario":"ieyasu1570","savedAt":"2026-09-28T10:30:00.000Z","point":"departure","playTimeSec":600,"phase":"battle","policy":"home","trust":{"oda":30,"asai":10,"tadakatsu":40},"troops":{"honjin":300,"tadakatsu":450,"yumi":350,"reserve":300},"characters":{"ieyasu":"alive","tadakatsu":"alive","nobunaga":"alive","nagamasa":"alive"},"talked":{"explore.tadakatsu":true,"council.council":true,"muster.tadakatsu":true,"muster.gate":true},"pledge":{"accepted":false,"partner":"tadakatsu","targetId":"t_reserve","result":"declined"},"battle":null,"battleId":"ieyasu1570-field","appliedBattleId":null,"support":null,"ending":null,"explore":null}';

/** 戦後・B 浅井・撤退・約束を守った（援兵あり） */
export const IEYASU_V1_AFTERMATH_ASAI =
    '{"version":1,"scenario":"ieyasu1570","savedAt":"2026-09-28T11:00:00.000Z","point":"aftermath","playTimeSec":1234,"phase":"aftermath","policy":"asai","trust":{"oda":0,"asai":35,"tadakatsu":40},"troops":{"honjin":290,"tadakatsu":350,"yumi":330,"reserve":300},"characters":{"ieyasu":"alive","tadakatsu":"alive","nobunaga":"alive","nagamasa":"alive"},"talked":{"explore.tadakatsu":true,"council.council":true,"muster.asai_envoy":true,"muster.gate":true},"pledge":{"accepted":true,"partner":"asai","targetId":"a_nagamasa","result":"kept"},"battle":{"result":"retreat","reason":"ordered_retreat","elapsedSec":300,"units":[{"id":"t_honjin","side":"ally","clan":"tokugawa","startStrength":300,"endStrength":240,"status":"withdrawn","leaderId":"ieyasu"},{"id":"t_tadakatsu","side":"ally","clan":"tokugawa","startStrength":450,"endStrength":300,"status":"withdrawn","leaderId":"tadakatsu"},{"id":"t_yumi","side":"ally","clan":"tokugawa","startStrength":350,"endStrength":280,"status":"withdrawn"},{"id":"a_nagamasa","side":"ally","clan":"asai","startStrength":400,"endStrength":320,"status":"withdrawn","leaderId":"nagamasa"},{"id":"e_oda_hq","side":"enemy","clan":"oda","startStrength":350,"endStrength":280,"status":"ready"},{"id":"e_oda_sente","side":"enemy","clan":"oda","startStrength":550,"endStrength":440,"status":"ready"},{"id":"e_oda_teppo","side":"enemy","clan":"oda","startStrength":350,"endStrength":280,"status":"ready"},{"id":"e_oda_kiba","side":"enemy","clan":"oda","startStrength":250,"endStrength":200,"status":"ready"}],"pledge":{"targetId":"a_nagamasa","result":"kept"},"abilitiesUsed":{"a_nagamasa":40}},"battleId":"ieyasu1570-v1fixture","appliedBattleId":"ieyasu1570-v1fixture","support":{"reinforcement":true,"from":"asai","recovered":150,"carryOver":["policy_asai","pledge_kept","reinforcement_asai"]},"ending":null,"explore":null}';

/** 結末・B 浅井・撤退（上の戦後から締めくくった） */
export const IEYASU_V1_ENDING_ASAI =
    '{"version":1,"scenario":"ieyasu1570","savedAt":"2026-09-28T11:00:00.000Z","point":"ending","playTimeSec":1234,"phase":"ending","policy":"asai","trust":{"oda":0,"asai":35,"tadakatsu":40},"troops":{"honjin":290,"tadakatsu":350,"yumi":330,"reserve":300},"characters":{"ieyasu":"alive","tadakatsu":"alive","nobunaga":"alive","nagamasa":"alive"},"talked":{"explore.tadakatsu":true,"council.council":true,"muster.asai_envoy":true,"muster.gate":true,"aftermath.tadakatsu":true},"pledge":{"accepted":true,"partner":"asai","targetId":"a_nagamasa","result":"kept"},"battle":{"result":"retreat","reason":"ordered_retreat","elapsedSec":300,"units":[{"id":"t_honjin","side":"ally","clan":"tokugawa","startStrength":300,"endStrength":240,"status":"withdrawn","leaderId":"ieyasu"},{"id":"t_tadakatsu","side":"ally","clan":"tokugawa","startStrength":450,"endStrength":300,"status":"withdrawn","leaderId":"tadakatsu"},{"id":"t_yumi","side":"ally","clan":"tokugawa","startStrength":350,"endStrength":280,"status":"withdrawn"},{"id":"a_nagamasa","side":"ally","clan":"asai","startStrength":400,"endStrength":320,"status":"withdrawn","leaderId":"nagamasa"},{"id":"e_oda_hq","side":"enemy","clan":"oda","startStrength":350,"endStrength":280,"status":"ready"},{"id":"e_oda_sente","side":"enemy","clan":"oda","startStrength":550,"endStrength":440,"status":"ready"},{"id":"e_oda_teppo","side":"enemy","clan":"oda","startStrength":350,"endStrength":280,"status":"ready"},{"id":"e_oda_kiba","side":"enemy","clan":"oda","startStrength":250,"endStrength":200,"status":"ready"}],"pledge":{"targetId":"a_nagamasa","result":"kept"},"abilitiesUsed":{"a_nagamasa":40}},"battleId":"ieyasu1570-v1fixture","appliedBattleId":"ieyasu1570-v1fixture","support":{"reinforcement":true,"from":"asai","recovered":150,"carryOver":["policy_asai","pledge_kept","reinforcement_asai"]},"ending":"retreat","explore":null}';
